on: [workflow_dispatch]

jobs:
  do-build:
    runs-on: ubuntu-latest
    name: build iso
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Containerized Build
        uses: ./

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/*.iso
